### PR TITLE
Fixup UDFPS icons and animations for multi-user

### PR DESCRIPTION
**Pull request by flakeforever**
**Issue 1:**
In this code snippet, due to always getting the UDFPS_ICON of the default user, when switching to another user, if the system default udfps icon is used, SystemUI enters a crash loop after the first lock screen.

https://github.com/Evolution-XYZ/frameworks_base/blob/9aa3f2944129cd85bb3822a8f32226c154cb14ac/packages/SystemUI/src/com/android/systemui/biometrics/UdfpsKeyguardViewLegacy.java#L138-L139

crash log:
https://paste.evolution-x.org/N4Cd0y

And in all the code related to UDFPS_ICON in SystemUI, they only get it for the default user, which clearly does not support multi-user.

**Solution:**
Considering that multi-user is a core feature provided by AOSP, this feature should not be broken. Therefore, I have fixed this issue in a single commit.
https://github.com/Evolution-XYZ/frameworks_base/commit/59f40f64bd8c8ece7a02ae5da304f3912c9e4a2d

**Issue 2:**
In contrast to UDFPS_ICON, this code snippet considers multi-user when getting UDFPS_ANIM_STYLE.
https://github.com/Evolution-XYZ/frameworks_base/blob/9aa3f2944129cd85bb3822a8f32226c154cb14ac/packages/SystemUI/src/com/android/systemui/biometrics/UdfpsAnimation.java#L122-L123

But, listens udfpsAnimStyle in the constructor, causing it to listen for changes only from the default user.
https://github.com/Evolution-XYZ/frameworks_base/blob/9aa3f2944129cd85bb3822a8f32226c154cb14ac/packages/SystemUI/src/com/android/systemui/biometrics/UdfpsAnimation.java#L130-L132

When setting UDFPS animations on a non-default user, the new settings are not taking effect.

**Solution:**
I have fixed this issue in a single commit.
Add a BroadcastReceiver for ACTION_USER_SWITCHED and re-register the listener after a user switch. 
https://github.com/Evolution-XYZ/frameworks_base/commit/0141d47d36b2ed86dd2e7af2b0c18a22715f7bd3

**Testing:**
I have completed testing for the two commits, including dirty installation and fresh installation. 
I created multiple users and set different UDFPS icons (including the system default) and UDFPS animations (including disabling animations).

### CODE REVIEW

**Comment by joeyhuab** [comment]
Nice findings and glad testing went well. Sorry as I currently do not have my UDFPS device for testing this.

**Comment by flakeforever** [comment]
Sure, I hope others can validate those commits.

**Comment by joeyhuab** [comment]
> Sure, I hope others can validate those commits.

You might want to make the same changes here: https://github.com/Evolution-XYZ/packages_apps_Evolver/blame/7807eb90978929a7d3616225fcb1e58fe13862ce/src/org/evolution/settings/fragments/themes/UdfpsAnimations.java#L138

**Comment by joeyhuab** [comment]
> > Sure, I hope others can validate those commits.
> 
> You might want to make the same changes here: [Evolution-XYZ/packages_apps_Evolver@`7807eb9`/src/org/evolution/settings/fragments/themes/UdfpsAnimations.java#L138 (blame)](https://github.com/Evolution-XYZ/packages_apps_Evolver/blame/7807eb90978929a7d3616225fcb1e58fe13862ce/src/org/evolution/settings/fragments/themes/UdfpsAnimations.java#L138)

Scratch that, we'll handle it!

**Comment by flakeforever** [comment]
In a multi-user environment, each user has its own evolver app process, so the default user under the each user is itself. No modifications are needed in this case.

**Comment by flakeforever** [comment]
And SystemUI is unique.

**Pull request merged**
